# Dependencies
markdown:             redcarpet
highlighter:          pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:            pretty
relative_permalinks:  true

# Setup
title:                iMaZe.de
tagline:              'The home of me'
url:                  http://www.imaze.de
baseurl:              /
paginate:             1

# About/contact
author:
  name:               Markus Buch
  email:              markus@imaze.de
  twitter:            https://twitter.com/elliot2extreme

# Custom vars
version:              1.0.0
