# Permalinks
permalink:            pretty
relative_permalinks:  true

# Setup
title:                iMaZe.de
tagline:              The home of me
url:                  http://www.imaze.de
paginate:             1
baseurl:              /
author:
  name:               Markus Buch
  email:              markus@imaze.de
